# Generated by Django 5.2.5 on 2026-09-01 12:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_profile_join_date_alter_profile_bio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_rejected', models.BooleanField(default=False)),
                ('from_who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_who', to=settings.AUTH_USER_MODEL)),
                ('to_who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_who', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('since_when', models.DateTimeField(default=django.utils.timezone.now)),
                ('greater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_greater', to=settings.AUTH_USER_MODEL)),
                ('lesser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_lesser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('lesser', 'greater'), name='unique_friend'), models.CheckConstraint(condition=models.Q(('lesser__lt', models.F('greater'))), name='lesser_id_smaller_than_greater_id')],
            },
        ),
    ]
