# Generated by Django 5.2.5 on 2026-09-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_alter_profile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='elo',
            field=models.IntegerField(default=100),
        ),
    ]
