# Generated by Django 5.2.5 on 2026-09-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_friendrequests_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='achievement',
            field=models.CharField(default='', max_length=100),
        ),
    ]
