# Generated by Django 5.2.5 on 2026-09-21 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_profile_join_date_alter_profile_bio_and_more'),
        ('models', '0003_stats_elo'),
    ]

    operations = [
    ]
