# Generated by Django 5.2.5 on 2026-09-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_stats_elo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='duration',
        ),
        migrations.AddField(
            model_name='stats',
            name='achievement',
            field=models.CharField(default='10000000000000000000000000000000000000000000000000', max_length=100),
        ),
        migrations.AddField(
            model_name='stats',
            name='streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='used_skin',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(default='FR', max_length=2),
        ),
    ]
