# Generated by Django 5.2.5 on 2026-09-15 13:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_stats_elo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_from_leser', models.BooleanField(default=True)),
                ('message', models.CharField(default='', max_length=100)),
                ('greater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_greater', to=settings.AUTH_USER_MODEL)),
                ('lesser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_lesser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Friendness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('since_when', models.DateTimeField(default=django.utils.timezone.now)),
                ('greater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='greater', to=settings.AUTH_USER_MODEL)),
                ('lesser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, 'pending'), (1, 'rejected')], default=0)),
                ('from_who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_who', to=settings.AUTH_USER_MODEL)),
                ('to_who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_who', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
