# Generated by Django 5.2.5 on 2026-09-17 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_friendmessage_friendness_friendrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='state',
        ),
    ]
